**Numpy:**


1.   Creating Numpy Arrays:


      *   Creating 1 D array
      *   Creating 2 D array





**Creating 1D array:**
1D array is created using


1.   list of elements
2.   arange()
3.   linspace()
4.   zeros()
5.   ones()



In [ ]:
import numpy as np

In [ ]:
# Creating 1D array using python list
# let us crate a list of elements
x=[10,20,30,40,50] # List values are separated by comma
print(x)
print(type(x))

# Let us convert x into numpy array
a=np.array(x) # Array values are separated by spaces
print(a)
print(type(a))

[10, 20, 30, 40, 50]
<class 'list'>
[10 20 30 40 50]
<class 'numpy.ndarray'>


In [ ]:
# Difference between List and array
# In list elements are separated by comma and in array elements are separated by space
# List is a python data structure, array is numpy data structure
# list is heterogeneous, array is homogeneous
# Array operations are very fast as compared to list
# Numpy array stores daa in continuous memory locations whereas list sotre data in random locations
# Numpy array are memory efficient

In [ ]:
# Element-wise addition of list elements
# check time of execution

x = [i for i in range(10000000)]
y = [i for i in range(10000000,20000000)]
z = []
import time
start = time.time()
for i in range(len(x)):
  z.append(x[i] + y[i])

print(time.time()-start)

1.9693961143493652


In [ ]:
# addition of numpy array elements
# check time of execution. It is less as compared to list

x = np.arange(10000000)
y = np.arange(10000000,20000000)

start = time.time()
z = x + y
print(time.time()-start)

0.201765775680542


In [ ]:
# List
L = [i for i in range(10000000)]
import sys
sys.getsizeof(L)

89095160

In [ ]:
# Numpy array
# Memory used by Numpy array is less than list
N = np.arange(10000000,dtype = np.int16)
sys.getsizeof(N)

20000112

**arange():** It is used to create an array using sequence of numbers. This can be used in three ways.


1.   np.arange(n)
2.   np.arange(st,n)
3.   np.arange(st,n,d)

*Note: arange() is used with floating point numbers also.*

Syntax: np.arange(start, stop, step, dtype=None)



In [ ]:
# arange()
a1=np.arange(5)
print(a1)
print(type(a1))

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
# Example 2
a2=np.arange(90,101)
print(a2)
print(type(a2))

[ 90  91  92  93  94  95  96  97  98  99 100]
<class 'numpy.ndarray'>


In [ ]:
# example 3
a3=np.arange(100,201,10)
print(a3)
print(type(a3))

[100 110 120 130 140 150 160 170 180 190 200]
<class 'numpy.ndarray'>


In [ ]:
# Example 4
# Working with floating point numbers
# range() can not have floating point value as a step value
a4=np.arange(0,1,0.1)
print(a4)
print(type(a4))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
<class 'numpy.ndarray'>


In [ ]:
# Example - 5
a41=np.arange(90,100,0.5)
print(a41)

[90.  90.5 91.  91.5 92.  92.5 93.  93.5 94.  94.5 95.  95.5 96.  96.5
 97.  97.5 98.  98.5 99.  99.5]


**np.linspace():** It is used to create an array with equidistance points between two values.

In [ ]:
# Example - 1
a5=np.linspace(0,100,10)
print(a5)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [ ]:
# Example - 2
a51=np.linspace(0,100,20)
print(a51)
print(len(a51))

[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]
20


In [ ]:
# Example 3
a52=np.linspace(0,100,50)
print(a52)
print(len(a52))

[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]
50


In [ ]:
# Example - 4
# create an array with 50 numbers which are inbetween 0 and 1
b=np.linspace(0,1,50)
print(b)
print(len(b))

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]
50


**np.zeros():** It is used to create an array with all the elements as zeros.

Syntax: np.zeros(shape, dtype=float) dtype is optional

In [ ]:
# Example - 1
a6=np.zeros(5) # numpy utilizes float as its default datatype
print(a6) # So answer is 0. is equivalent to 0.0

[0. 0. 0. 0. 0.]


In [ ]:
# Example - 2 : we can mention data type of an element
a61=np.zeros(9,dtype=int)
print(a61)
print(len(a61))

[0 0 0 0 0 0 0 0 0]
9


**np.ones():** It create an array with all its elements as ones.

In [ ]:
# Example - 1
a7=np.ones(5,dtype=int)
print(a7)
print(len(a7))

[1 1 1 1 1]
5


In [ ]:
# Example - 2
a71=np.ones(20,dtype=int)
print(a71)
print(len(a71))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
20


In [ ]:
# create an array with 5 repeated 50 times.
m=np.ones(50,dtype=int)
n=m*5
print(m)
print(n)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5]


**Creating 2D Arrays:**
2D arrays are created using



1.   Multiple lists [array()]
2.   zeros()
3.   ones()
4.   eye()
5.   2D arrays can be created by reshaping of 1D arrays.



In [ ]:
import numpy as np
# creating 2D array using multiple lists
# example -1
b1=np.array([[1,2],[3,4]])
print(b1)
print(type(b1))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [ ]:
# Example - 2
b11=np.array([[1,0,0],[0,1,0],[0,0,1]])
print(b11)
print(type(b11))

[[1 0 0]
 [0 1 0]
 [0 0 1]]
<class 'numpy.ndarray'>


In [ ]:
# Example - 3
b12=np.array([[1,2,3],[3,4,5]])
print(b12)
print(type(b12))

[[1 2 3]
 [3 4 5]]
<class 'numpy.ndarray'>


# **Creating 2-D array Using Zeros**

In [ ]:
# Example - 1
b2=np.zeros([5,8])
print(b2)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# Example - 2
b21=np.zeros([3,4])
print(b21)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Example - 3
b22=np.zeros((3,3))
print(b22)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# **Creating 2-D Arrays With Ones**

In [ ]:
# Example - 1
b3=np.ones([10,12])
print(b3)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
# Example - 2
b31=np.ones((3,3))
print(b31)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# **Creating Identity Array**

1s on the main diagonal, 0s everywhere else.

np.eye(N, M=None, k=0, dtype=float)

N: No. of rows

M: No. of col (optional)

K: diagonal index

In [ ]:
# Exmaple - 1
b4=np.eye(5)
print(b4)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
arr=np.eye(5,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Example - 2
b41=np.eye(3)
print(b41)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
b41=np.eye(3,k=1)
print(b41)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [ ]:
b41=np.eye(3,k=-1)
print(b41)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


**Attribute of Numpy Arrays:**



1.   **Dimensionality** : array_var_name.ndim
2.   **Size:** it gives total count of elements in an array - array_var_name.size
3.   **Shape:** it gives total rows and coumns in an array - arra_var_name.shape
4.   **DataType:** it gives data type of an array - array_var_name.dtype
5.   **itemsize:** it gives memory allocated per element in an array - arra_var_name.itemsize



In [ ]:
# Example - 2
# Let us create a 2D array
x=np.eye(4)
print("Identity Array")
print(x)

# Let us verify the dimensionality of x
print("No. of Dimensions: ",x.ndim)

# Let us verify the size of x
print("Total Elements: ",x.size)

# Let us verify the shape of x
print("Total Rows and Columns: ",x.shape)

# Let us verify the data type of an element in x
print("Datatype: ",x.dtype)

# Let us verify the itemsize of x
print("Memory: ",x.itemsize)

Identity Array
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
No. of Dimensions:  2
Total Elements:  16
Total Rows and Columns:  (4, 4)
Datatype:  float64
Memory:  8


In [ ]:
# Example - 2
# Let us create a 1D array and verify all attribute of an array
y=np.arange(-10,11,2)
print(y)
print(len(y))

[-10  -8  -6  -4  -2   0   2   4   6   8  10]
11


In [ ]:
# Let us verify the dimensionality of y
print(y.ndim)

1


In [ ]:
# Let us verify the size of y
print(y.size)

11


In [ ]:
# Let us verify the shape of y
print(y.shape)
# The array has 1 dimension, That dimension has 11 elements
# NumPy does NOT think in terms of rows and columns by default.
# So output is (11,)

(11,)


In [ ]:
# Let us verify the data type of y
print(y.dtype)

int64


In [ ]:
# Let us verfy the itemsize
print(y.itemsize) # 8 bytes i.e. 64 bits

8


In [ ]:
b4=np.eye(5)
print(b4)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# size of an array (product of rows * columns)
print(b4.size)

25


In [ ]:
# shape of an array (number of rows and colums)
print(b4.shape)

(5, 5)


In [ ]:
# dtype: data type of elements in an array
print(b4.dtype)
print(type(b4))

float64
<class 'numpy.ndarray'>


In [ ]:
# itemsize: memory of each element in bytes.
print(b4.itemsize)

8


In [ ]:
# create 1D array 10 elements and check all attributes.
p=np.arange(-20,21,2)
print(p)
print(p.ndim)
print(p.size)
print(p.shape)
print(p.dtype)
print(p.itemsize)

[-20 -18 -16 -14 -12 -10  -8  -6  -4  -2   0   2   4   6   8  10  12  14
  16  18  20]
1
21
(21,)
int64
8


**Copying an Array:**
array_var_name.copy(): to copy the data of an array in another.

In [ ]:
# copying the data of an array into another array.
x1=np.array([[1,2,3],[4,5,6],[9,9,9]])
print(x1)

[[1 2 3]
 [4 5 6]
 [9 9 9]]


In [ ]:
# data in x1 is copied into y1
y1=x1.copy()  # Deep Copy
# A new array is created with same data at separate memory location
print(y1)

[[1 2 3]
 [4 5 6]
 [9 9 9]]


In [ ]:
print(x1 is y1)

False


In [ ]:
# change in y1 doesn't change x1
y1[0,0] = 500
print(x1)

[[1 2 3]
 [4 5 6]
 [9 9 9]]


In [ ]:
print(y1)

[[500   2   3]
 [  4   5   6]
 [  9   9   9]]


In [ ]:
# alternative method for copy
z1=x1   # shallow copy (aliasing). This is assignment
# No new array is created
# z1 and x1 point to the same memory
# This is just another name for the same array
print(z1)

[[1 2 3]
 [4 5 6]
 [9 9 9]]


In [ ]:
print(x1 is z1)

True


In [ ]:
# if you change element of z1, it is reflected to x1
z1[0,0] = 100
print(x1)

[[100   2   3]
 [  4   5   6]
 [  9   9   9]]


In [ ]:
# Practice Questions:
# Q1: create an array with 3 rows and 6 columns.
# Q2: create an array with numbers starting from 888 to 999.
# Q3: create an array with shape (12,10) with zeros as its elements
# Q4:create an array with shape (15,14) with 99 as its elements.
# Q5:create an array with shape (11,6) with 5 as its elements
     # and check its shape, size, dimensionality, data type,itemsize.

In [ ]:
z3=np.arange(888,1000)
print(z3)

[888 889 890 891 892 893 894 895 896 897 898 899 900 901 902 903 904 905
 906 907 908 909 910 911 912 913 914 915 916 917 918 919 920 921 922 923
 924 925 926 927 928 929 930 931 932 933 934 935 936 937 938 939 940 941
 942 943 944 945 946 947 948 949 950 951 952 953 954 955 956 957 958 959
 960 961 962 963 964 965 966 967 968 969 970 971 972 973 974 975 976 977
 978 979 980 981 982 983 984 985 986 987 988 989 990 991 992 993 994 995
 996 997 998 999]


In [ ]:
import numpy as np
z=np.ones([15,14])
z2=z*99
print(z2)

[[99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]]


In [ ]:
import numpy as np
z=np.ones([11,6])
z2=z*5
print(z2)

[[5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]]
