In [1]:
import numpy as np

### **More ways to create array**


# **np.diag():** Extract a diagonal or construct a diagonal array.

In [2]:
# Example - 1
# Creating new 1D array using diagonal elements of another 2Darray
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
b=np.diag(a) # principal diagonal printed
print("\n")
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[1 5 9]


In [3]:
# Example - 2
b1=np.diag(a,1)
print(b1)

[2 6]


In [4]:
# Example - 3
b1=np.diag(a,2)
print(b1)

[3]


In [5]:
# Example - 4
b2=np.diag(a,-1)
print(b2)

[4 8]


In [6]:
# Example - 5
b2=np.diag(a,-2)
print(b2)

[7]


# **np.full():** Return a new array of given shape and type, filled with fill_value.


*   fill_value can be any number/list.



In [7]:
# Example - 1
f=np.full([3,3],fill_value=0)
print(f)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:
# Example - 2
f=np.full([3,6],fill_value=18)
print(f)

[[18 18 18 18 18 18]
 [18 18 18 18 18 18]
 [18 18 18 18 18 18]]


In [9]:
# Example - 3
f11=np.full([3,3],fill_value=np.nan)
print(f11)

[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]


In [10]:
# Example - 4
f1=np.full([3,3],fill_value=np.inf) # infinite values
print(f1)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


In [11]:
# Example - 5
f2=np.full([3,3],fill_value=[1,2,3]) # fill with a list
print(f2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [12]:
f21=np.array([[1],[2],[3]])
print(f21)

[[1]
 [2]
 [3]]


In [ ]:
# Example - 6
f2=np.full([3,3],fill_value=[[1],[2],[3]])
print(f2)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


# **np.random:** random number generator in numpy



1.   **np.random.rand(r,c):** it generate array with random values between 0 and 1 having given rows and columns. Contains float values.

2.   **np.random.randint(low, high, size):** it generate array of integers with random numbers within given range.

3.   **np.random.randn():** it generates array with random Normal (Gaussian) Distribution where mean is 0 and standard deviation is 1.

In [14]:
# Example - 1
# creating 2D array of required shape with random data (0-1)
r=np.random.rand(3,5)
print(r)

[[0.58846788 0.08585669 0.38264003 0.11550142 0.87746885]
 [0.25643989 0.28088174 0.20866994 0.24143387 0.01257638]
 [0.02019042 0.36018333 0.43180796 0.56477774 0.56244505]]


In [15]:
# Example - 2
r2=np.random.rand(10,10)
print(r2)

[[6.73161026e-01 2.11269829e-01 8.89426131e-01 5.77018489e-01
  2.59936700e-01 3.73984866e-01 5.27899559e-01 8.69904317e-01
  8.58844022e-02 6.09487400e-02]
 [6.47005248e-01 8.71320748e-01 1.59780136e-01 7.38683838e-01
  1.98099909e-01 3.24727016e-01 5.04968518e-01 4.99877964e-01
  3.28783958e-01 5.25863691e-01]
 [1.20939700e-01 3.87458738e-01 7.36339050e-02 8.62544135e-03
  9.58362944e-01 6.51907701e-01 1.11637705e-01 6.07835080e-01
  4.41314638e-01 8.51460964e-02]
 [9.20493499e-01 8.17521297e-01 4.54077043e-01 6.75991339e-01
  2.15750269e-01 8.53735117e-01 6.32264282e-01 7.29773453e-01
  2.64444595e-01 2.92639117e-01]
 [9.55313545e-01 3.05434785e-01 7.47572218e-01 6.55412752e-01
  6.14339600e-01 7.96740594e-01 8.71729764e-01 3.37467427e-01
  2.25685785e-01 3.97023706e-01]
 [1.39107341e-01 1.80885488e-01 3.66138892e-01 4.24167908e-01
  7.47861609e-01 2.68846685e-01 2.92838337e-01 2.87282310e-01
  7.50068504e-01 5.84624088e-01]
 [5.41880924e-01 4.80267472e-01 6.58715683e-01 9.03928292e

In [17]:
# Example - 3
# creating 1D array with random elements.
r1=np.random.randint(1,size=5) # 1: indicates only one random value from 0,
                               # size is no. of elements in array
print(r1)

[0 0 0 0 0]


In [20]:
# Example - 4
r2=np.random.randint(2,size=5) # 2: random no can be 0 or 1
print(r2)

[1 1 1 0 0]


In [22]:
r2=np.random.randint(3,size=5) # 3: random no can be 0 or 1 or 2
print(r2)

[2 2 1 2 0]


In [23]:
# Example - 5
r3=np.random.randint(5,size=50)
print(r3)

[4 3 3 1 3 4 4 0 0 4 4 4 4 4 0 2 2 2 4 1 2 1 4 2 3 2 2 0 2 2 2 0 1 2 1 3 4
 4 0 2 3 0 4 0 1 1 0 4 0 0]


In [24]:
# Exapmle - 6
r4=np.random.randint(10,15,size=10)
print(r4)

[14 13 11 11 10 13 10 13 10 10]


In [25]:
# Example - 7
rn=np.random.randn(5) # it generates array with random normal distribution.
# In Standard Normal Distribution, Mean (μ) = 0
# Standard deviation (σ) = 1
# So values are:
# Mostly around 0
# Can be positive or negative, decimal
# No fixed min/max range (theoretically −∞ to +∞)
print(rn)

[0.35606325 1.22684847 0.65140961 0.98567799 1.01400008]


In [27]:
# Example - 8
rn=np.random.randn(3,5) # 3 rows, 5 columns
print(rn)

[[ 0.12159285  0.51289318  0.5850058  -1.16708466 -1.10352776]
 [-0.28702026 -2.34852217 -0.39756003  1.32236752 -0.35492481]
 [ 0.41976281  0.9083547   1.28502027 -0.58466171  1.34699933]]


In [28]:
# Example - 9
rn=np.random.randn() #
print(rn)

0.9938355031804607


In [ ]:
# create a 2D array of 100,200 shape with random data
# create a 1D array with 101 elements with random data

# **Indexing and Slicing in Arrays:**



1.   Indexing in 1D Array.

2.   Slicing in 1D array.

3.   Indexing in 2D Array.

4.   Slicing in 2D array.

In [29]:
# Slicing in 1D Arrays:
x=np.arange(-10,11,2)
print(x)

[-10  -8  -6  -4  -2   0   2   4   6   8  10]


In [31]:
print(x[8]) # we are expecting element with index 4 in array x.

6


In [32]:
print(x[2:6])

[-6 -4 -2  0]


In [33]:
print(x[0:8:2])

[-10  -6  -2   2]


**Indexing and Slicing in a 2D Array:**


1.    A 2D array has multiple rows and columns.
2.    There are two index values. One for row index and other for column index.
3.    Always the index value starts from 0.
4.    *syntax to access an element is:  arrayname[row_idx,col_idx]*

# Example - 1
a=np.eye(5)
print(a)

In [34]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [35]:
# Let us access an element from a
# syntax ---> array_variable_name [row_index, col_index]
print(a[0,0])

1.0


In [36]:
print(a[1,1])

1.0


In [39]:
# Let us access first row
a[0:1,1:5]

array([[0., 0., 0., 0.]])

In [41]:
a[3,1:4]

array([0., 0., 1.])

In [ ]:
# write code to access all the rows (one at a time)
a[1,1:5]

array([1., 0., 0., 0.])

In [42]:
# let us access first column elements
a[0:5,0:1]

array([[1.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [43]:
d=np.array([[1,2,3,4,5],[5,4,3,2,1],[4,5,6,7,8],[8,9,5,3,1]])
print(d)
print(d[0,0])
print(d[3,4])

[[1 2 3 4 5]
 [5 4 3 2 1]
 [4 5 6 7 8]
 [8 9 5 3 1]]
1
1


In [ ]:
# access first 2 rows and first 2 columns individually from above array

In [44]:
d[0:1,0:5] # first row

array([[1, 2, 3, 4, 5]])

In [45]:
d[0:4,0:1] # first column

array([[1],
       [5],
       [4],
       [8]])

**Indexing With Boolean Arrays:**


1.   It helps in selecting array elements.




In [46]:
# 1-D Array:
b=np.arange(100,116)
print(b)
print(b[b>=112])

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115]
[112 113 114 115]


In [48]:
# 2-D Arrays:
b1=np.array([[1,7,4],[5,2,8],[1,0,2]])
print(b1)
print('\n')
print(b1[b1>=4])

[[1 7 4]
 [5 2 8]
 [1 0 2]]


[7 4 5 8]


**Arithmetic Operations on Arrays:**



1.   +,-,*,/,//,%,**
2.   The arithmetic operations are performed b/w either two 1D arrays or in b/w two 2D arrays.
3.   The arrays must should have same shape (rows,col).




In [52]:
# Arithmetci Operation on 1D arrays:
x=np.arange(-10,11,2)
y=np.arange(10,-11,-2)
print(x)
print(y)
print(len(x))
print(len(y))

[-10  -8  -6  -4  -2   0   2   4   6   8  10]
[ 10   8   6   4   2   0  -2  -4  -6  -8 -10]
11
11


In [53]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)

[0 0 0 0 0 0 0 0 0 0 0]
[-20 -16 -12  -8  -4   0   4   8  12  16  20]
[-100  -64  -36  -16   -4    0   -4  -16  -36  -64 -100]
[-1. -1. -1. -1. -1. nan -1. -1. -1. -1. -1.]
[0 0 0 0 0 0 0 0 0 0 0]


/tmp/ipython-input-574330594.py:4: RuntimeWarning: invalid value encountered in divide
  print(x/y)
/tmp/ipython-input-574330594.py:5: RuntimeWarning: divide by zero encountered in remainder
  print(x%y)


In [54]:
# Arithmetic Operation on 2D arrays:
x1=np.array([[1,2],[3,4]])
x2=np.ones([2,2])
print(x1)
print(x2)
print(x1.shape)
print(x2.shape)

[[1 2]
 [3 4]]
[[1. 1.]
 [1. 1.]]
(2, 2)
(2, 2)


In [55]:
print(x1+x2)

[[2. 3.]
 [4. 5.]]


In [56]:
x = np.array([10,20,30])
y = np.array([3,4,5])

In [57]:
print(x//y)

[3 5 6]


In [58]:
print(x/y)

[3.33333333 5.         6.        ]


**Statistical Operations on Arrays:**
Following statistical parameters are computed for an array:


1.   min(): minimum value.
2.   max(): maximum value.
3.   sum(): sum of elements.
4.   mean(): average of elements in an array.
5.   median(): middle value.
6.   std(): standard deviation.
7.   var(): calculates variance.
8.   corrcoef(): pearson correlation coefficient.



In [59]:
# Statistical operations on 1D array
x=np.arange(-20,21,2)
print(x)

[-20 -18 -16 -14 -12 -10  -8  -6  -4  -2   0   2   4   6   8  10  12  14
  16  18  20]


In [60]:
# Statistical operations on 1D array:
print(x)
print(x.min())
print(x.max())
print(x.sum())
print(x.mean())
print(x.std())
print(x.var())
print(np.median(x))
#print(np.corrcoef(x,y))

[-20 -18 -16 -14 -12 -10  -8  -6  -4  -2   0   2   4   6   8  10  12  14
  16  18  20]
-20
20
0
0.0
12.110601416389967
146.66666666666666
0.0


In [ ]:
print(np.median(x))

0.0


In [61]:
# Statistical Operation on 2D array:
import numpy as np
x1=np.array([[1,2,6],[3,4,5],[0,8,5]])
print(x1)

[[1 2 6]
 [3 4 5]
 [0 8 5]]


In [62]:
# min()
print(x1.min())       # minimum value out of all the elements.
print(x1.min(axis=0)) # minimum values column wise.
print(x1.min(axis=1)) # minimum values row wise.

0
[0 2 5]
[1 3 0]


In [63]:
# max():
print(x1.max())       # maximum value out of all the elements.
print(x1.max(axis=0)) # maximum values column wise.
print(x1.max(axis=1)) # maximum values row wise.

8
[3 8 6]
[6 5 8]


In [64]:
# sum():
print(x1.sum()) # sum of all the elements in an array.
print(x1.sum(axis=0)) # column wise sum.
print(x1.sum(axis=1)) # row wise sum.

34
[ 4 14 16]
[ 9 12 13]


In [65]:
# mean()
print(x1.mean())
print(x1.mean(axis=0))
print(x1.mean(axis=1))

3.7777777777777777
[1.33333333 4.66666667 5.33333333]
[3.         4.         4.33333333]


In [66]:
# median()
print(np.median(x1))
print(np.median(x1,axis=0))
print(np.median(x1,axis=1))

4.0
[1. 4. 5.]
[2. 4. 5.]


In [67]:
# std()
print(x1.std())
print(x1.std(axis=0))
print(x1.std(axis=1))

2.3934065809486684
[1.24721913 2.49443826 0.47140452]
[2.1602469  0.81649658 3.29983165]


**Math Functions in Numpy:**
Numpy has many mathematical functions.



1.   np.sqrt(): square root of elements in an array.
2.   np.exp(): exponential of elements in an array.
3.   np.sin(): sine value of elements in an array in radians.
4.   np.cos(): cosine value of elements in an array in radians.
5.   np.add():
6.   np.subtract():
7.   np.multiply():
8.   np.divide():



In [ ]:
import numpy as np

In [68]:
x1=np.array([[1,2],[3,4]])

In [69]:
print(x1)

[[1 2]
 [3 4]]


In [70]:
# np.sqrt()
print(np.sqrt(x1))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [71]:
# np.exp()
print(np.exp(x1))

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


In [ ]:
# Trgonometric Functions.
print(np.sin(x1))
print(np.cos(x1))
print(np.tan(x1))

[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]
[[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]]
[[ 1.55740772 -2.18503986]
 [-0.14254654  1.15782128]]


In [ ]:
# add()
print(np.add(x1,10))
print("\n")
print(np.subtract(x1,10))
print("\n")
print(np.multiply(x1,0))
print("\n")
print(np.divide(x1,10))

[[11 12]
 [13 14]]


[[-9 -8]
 [-7 -6]]


[[0 0]
 [0 0]]


[[0.1 0.2]
 [0.3 0.4]]
